import loginPage from "../../../support/Project_Akhir/Login/loginPage"
import loginData from "../../../fixtures/Project_Akhir/Login/loginData"
import directoryPage from "../../../support/Project_Akhir/Directory/directoryPage"
import directoryData from "../../../fixtures/Project_Akhir/Directory/directoryData"


describe('Test Scenario Directory', () => {
    it('TC001-Search Employee by Name', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.inputEmployeeName(directoryData.employeeName.shortName)
        directoryPage.autoCompletedEmployeeName(directoryData.employeeName.fullName)
        directoryPage.searchButton()
        directoryPage.verifyResults(directoryData.employeeName.fullName)
    })

    it('TC002-Search Employee by Job Title', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.dropdwonJobTitle()
        directoryPage.chooseJobTitle(directoryData.jobTitle.job)
        directoryPage.searchButton()
        directoryPage.verifyJobTitle(directoryData.jobTitle.job)
    })

    it('TC003-Search Employee by Job Location', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.dropdwonLocation()
        directoryPage.chooseLocation(directoryData.location.locationName)
        directoryPage.searchButton()
        directoryPage.verifyLocation(directoryData.location.locationName)
    })

    it('TC004-Search Employee by Invalid Name', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.inputEmployeeName(directoryData.invalidEmployee.shortName)
        directoryPage.searchButton()
        directoryPage.invalidEmployeeError()
    })

    it('TC005-Reset button after Search Job Title', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.dropdwonJobTitle()
        directoryPage.chooseJobTitle(directoryData.jobTitle.job)
        directoryPage.searchButton()
        directoryPage.verifyJobTitle(directoryData.jobTitle.job)
        directoryPage.resetButton()
        directoryPage.verifyReset()
    })

    it('TC006-Search empty', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.searchButton()
        directoryPage.verifyReset()

    })

    it('TC007-Search Employee Name, Job Title, and Location', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.inputEmployeeName(directoryData.employeeName.shortName)
        directoryPage.autoCompletedEmployeeName(directoryData.employeeName.fullName)
        directoryPage.dropdwonJobTitle()
        directoryPage.chooseJobTitle(directoryData.jobTitle.job)
        directoryPage.dropdwonLocation()
        directoryPage.chooseLocation(directoryData.location.locationName)
        directoryPage.searchButton()
        directoryPage.verifyResults(directoryData.employeeName.fullName)
        directoryPage.verifyJobTitle(directoryData.jobTitle.job)
        directoryPage.verifyLocation(directoryData.location.locationName)
    })

    it('TC008-Search Employee Name, Job Title, and Location with Invalid Job Title', () => {
        loginPage.visitPage()
        loginPage.inputUsername(loginData.validUser.username)
        loginPage.inputPassword(loginData.validUser.password)
        loginPage.clickLoginButton()
        loginPage.verifyLoginSuccess()
        directoryPage.visitDirectory()
        directoryPage.veryfyDirectoryPage()
        directoryPage.inputEmployeeName(directoryData.employeeName.shortName)
        directoryPage.autoCompletedEmployeeName(directoryData.employeeName.fullName)
        directoryPage.dropdwonJobTitle()
        directoryPage.chooseJobTitle(directoryData.invalidJobTitle.job)
        directoryPage.dropdwonLocation()
        directoryPage.chooseLocation(directoryData.location.locationName)
        directoryPage.searchButton()
        directoryPage.toastMessage()
    })

})